### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NickChang97** [thegreatmd4/numerical_methods#1]
Very thanks to your code. Can your tell when the Gauss_quadrature_Integrations.m will release

**Comment by thegreatmd4** [comment]
Dear NickChang97, thanks for your comment. I'm really glad to see someone uses my codes.
I just didn't really understand what your question is. I have already published "Gauss_quadrature_Integrations.m". If you have any problem to run the script, I'll be glad to help you.

**Comment by NickChang97** [comment]
Thanks for your reply.  In the file of Gauss_quadrature_Integrations.m, there is only three lines

```
clc;
clear;
close all;
```

**Comment by thegreatmd4** [comment]
Oh my God. You're actually right! I just checked my original codes on my hard drive, and it was empty too. Give me some time, and I'll work on it. Thanks for your note.

**Comment by NickChang97** [comment]
> Oh my God. You're actually right! I just checked my original codes on my hard drive, and it was empty too. Give me some time, and I'll work on it. Thanks for your note.

Really thanks
